env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb-typescript
  - plugin:react/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  project:
    - tsconfig.json
settings:
  react:
    version: detect
plugins:
  - react
  - "@typescript-eslint"
  - prettier
  - import
ignorePatterns:
  - "**/dist/*"
rules:
  prettier/prettier: error
  no-unused-vars: off
  quotes: off
